#version: '2'
services:
#  app:
    image: default_image_name4-1
    container_name: service4-1
#    volumes:
#     - ../../shared/config/secrets.yml:/app/config/secrets.yml
#     - ../../shared/config/database.yml:/app/config/database.yml
    pid: "host"
    restart: always
    ports:
     - "80:80"
#    networks:
#      net:
#        ipv4_address: 192.168.3.2


#networks:
#  net:
#    driver: bridge
#    ipam:
#     config:
#       - subnet: 192.168.3.0/24
#         gateway: 192.168.3.1
